---
title: "Text Mining of Assemblé Generale Documents"
author: "ZIANI,MASSELIN,DIALLO,ANZID"
date: "March 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Package
install.packages("syuzhet")
install.packages("tm")
```

```{r}
library(rvest)
library(xml2)
library(stringi)
# Extraction de la page html d'une séance unique (123eme) du 22/02/2017
textTreeBase <- read_html("http://www.assemblee-nationale.fr/14/cri/2016-2017/20170123.asp")

# Extraction 
textSeance20170123<- textTreeBase %>% html_nodes("body") %>% html_nodes("p") %>% html_text() #extraction dans le noeud <body> puis dnas le noeud <p>

```

```{r}
library(stringr)
library(dplyr)
# Création d'un object Data
text_seance20170123 <- tibble(line = 1:length(textSeance20170123), text = textSeance20170123)

# utilisation des regex pour désigner les hommes et les femmes
sexeM <- c("M\\. ")
sexeF <- c("Mme ")

#On ne garde que les discour des hommes et femmes dicriminer par leur sexe
text_seance20170123 <- text_seance20170123 %>%
  rowwise() %>% 
  mutate(sexe = if(str_detect(text, sexeM)) "Homme" else if(str_detect(text, sexeF)) "Femme" else "autre") %>% 
  filter(sexe != "autre")
```

Les mot les plus utiliser pendant le débat
```{r}
library(tidytext)
library(ggplot2)
t <- text_seance20170123 %>% 
  unnest_tokens(word, text) %>%
  filter(!str_detect(word, "[0-9]"))

t %>%
  count(word, sort = TRUE) %>%
  filter(n > 100) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()

#Filtre les nombres dans les mots et calcule le nombres de mots identique en fonction du sexe
t2 <- t %>%
  count(word,sexe, sort = TRUE) %>%
```

Regroupe par sexe les mots les plus utilisé
```{r}

library(tidytext)
library(ggplot2)
t2 %>%
  group_by(sexe) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sexe)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sexe, scales = "free_y") +
  labs(y = "Les Mots Favoris", x = NULL) +
  coord_flip()

t2 %>%
  count(sexe, sort =F)
```


```{r}
#Les mots exclus
motstop <- read.delim("./stopword/stopwords-fr.txt")
motstop

t3 <-t2
t3 <- t3 %>%
  anti_join(motstop)
```
```{r}
#Les mots exclus
motstop2 <- read.delim("./stopword/stopword2-fr.txt")
motstop2

t4 <-t2
t4 <- t4 %>%
  anti_join(motstop2)
```




```{r}
t3 %>%
  group_by(sexe) %>%
  top_n(30) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sexe)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sexe, scales = "free_y") +
  labs(y = "Les Mots Favoris", x = NULL) +
  coord_flip()

t4 %>%
  group_by(sexe) %>%
  top_n(30) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sexe)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sexe, scales = "free_y") +
  labs(y = "Les Mots Favoris", x = NULL) +
  coord_flip()
```

```{r}

library(syuzhet)
library(tm)
library(ggplot2)
result <-get_nrc_sentiment(t[["word"]])
result1<-data.frame(t(result))
new_result <- data.frame(rowSums(result1))
names(new_result)[1] <- "count"
new_result <- cbind("sentiment" = rownames(new_result), new_result)
rownames(new_result) <- NULL
qplot(sentiment, data=new_result[1:8,], weight=count, geom="bar",fill=sentiment)+ggtitle("TedTalk Sentiments")
qplot(sentiment, data=new_result[9:10,], weight=count, geom="bar",fill=sentiment)+ggtitle("TedTalk Sentiments")

```

```{r}

t$word[t$sexe=="Femme"]->wordofWomen
t$word[t$sexe=="Homme"]->wordofMan

#partie Homme 
library(syuzhet)
library(tm)
library(ggplot2)
resultMan <-get_nrc_sentiment(wordofMan)
resultMan1<-data.frame(t(resultMan))
new_resultMan <- data.frame(rowSums(resultMan1))
names(new_resultMan)[1] <- "count"
new_resultMan <- cbind("sentiment" = rownames(new_resultMan), new_resultMan)
rownames(new_resultMan) <- NULL
qplot(sentiment, data=new_resultMan[1:8,], weight=count, geom="bar",fill=sentiment)+ggtitle("TedTalk Sentiments Homme ")
qplot(sentiment, data=new_resultMan[9:10,], weight=count, geom="bar",fill=sentiment)+ggtitle("TedTalk Sentiments Homme ")

#partie Femme 
library(syuzhet)
library(tm)
library(ggplot2)
resultWomen <-get_nrc_sentiment(wordofWomen)
resultWomen1<-data.frame(t(resultWomen))
new_resultWomen <- data.frame(rowSums(resultWomen1))
names(new_resultWomen)[1] <- "count"
new_resultWomen <- cbind("sentiment" = rownames(new_resultWomen), new_resultWomen)
rownames(new_resultMan) <- NULL
qplot(sentiment, data=new_resultWomen[1:8,], weight=count, geom="bar",fill=sentiment)+ggtitle("TedTalk Sentiments Femme")
qplot(sentiment, data=new_resultWomen[9:10,], weight=count, geom="bar",fill=sentiment)+ggtitle("TedTalk Sentiments Femme")


```


```{r}
# 
t  %>%   
  inner_join(get_sentiments("nrc")) %>%
  group_by(index = line %/% 25, sexe , sentiment) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = index, y = n, fill = sexe )) + 
  geom_bar(stat = "identity", alpha = 0.8) + 
  facet_wrap(~ sentiment, ncol = 5) 

 

```
